version: "3"
services:
  app:
    image: node-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - data-volume:/data

volumes:
  data-volume:
